Repository whtrapp/whtrapp.github.io, pull requests merged in 2024-10, with the labels that each got.

#11 Issue #7: Improving README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2024

#17 Documentation: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2024

#16 Enhancement: Add Explore Button with Day/Night Mode and Chevron Icon Update
  .vscode/settings.json
  css/style.css
  index.html
  js/main.js
Labels: enhancement, hacktoberfest, hacktoberfest2024

#12 Fix #5: Fix sidebar overflow
  css/style.css
Labels: bug, enhancement, hacktoberfest, hacktoberfest2024

#27 Fix #20: Add .vscode/settings.json file
  .vscode/settings.json
Labels: enhancement, hacktoberfest, hacktoberfest2024

#28 Fix #23, #25: Change scrollbar look to match the theme of app, Improving the JS
  css/style.css
  js/main.js
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest2024

#33 Fix #29: JavaScript Code Distribution
  index.html
  js/localStorage.js
  js/main.js
  js/uiController.js
  js/utils.js
  js/weatherApi.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#35 Fix #18: Add the feature of autocomplete on the search bar.
  css/style.css
  index.html
  js/main.js
  js/searchAutocomplete.js
  js/utils.js
Labels: enhancement, hacktoberfest, hacktoberfest2024

#9 Fix #8: Temporary Responsive Design
  css/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest2024

#39 Fix #26: Add a footer
  css/style.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#36 Fix #31: Adding Typing Effect for Dynamic Place Name
  index.html
  js/main.js
Labels: enhancement, hacktoberfest, hacktoberfest2024

#2 Fix #1: Time updates in real-time
  js/main.js
  js/timeAPI.js
Labels: enhancement, hacktoberfest, hacktoberfest2024

#45 Fix #43: Reposition Explore Button + Modify Styling
  css/style.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#46 Enhancement: Cursor Pointer in search bar, Fix Javascript
  css/style.css
  index.html
  js/main.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#50 Enhancement: Add spinner for weather data loading
  css/satoshi.css
  index.html
  js/main.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#51 Fix #38: Fetch an update every 60 minutes
  js/main.js
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest2024

#52 feat(alert): customize SweetAlert2 popup with custom styling
  css/style.css
  index.html
  js/main.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024
